cheese:
  master:
    datasource:
      url: jdbc:mysql://database-1.czu202wgm11k.ap-northeast-2.rds.amazonaws.com:3306/cheese
      username: admin
      password: 13546946
      hikari:
        minimum-idle: 15
        maximum-pool-size: 60
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true



